const ADD_TODO = "ADD_TODO"
const REMOVE_TODO = "REMOVE_TODO"
const MARK_COMPLETE = "MARK_COMPLETE"
const FETCH_TODOS = "FETCH_TODOS"
const DATABASE_SAVING = "DATABASE_SAVING"
const DATABASE_INSPECTING = "DATABASE_INSPECTING"
const ERROR = "ERROR"
const LOADING_DATA = "LOADING_DATA"
const AUTHENTICATED = 'AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
export {ADD_TODO, REMOVE_TODO, MARK_COMPLETE, FETCH_TODOS, DATABASE_INSPECTING, LOADING_DATA, DATABASE_SAVING, ERROR, AUTHENTICATED, NOT_AUTHENTICATED}