const ADD_TODO = "ADD_TODO"
const REMOVE_TODO = "REMOVE_TODO"
const MARK_COMPLETE = "MARK_COMPLETE"
const GET_TODOS = "GET_TODOS"
const DATABASE_SAVING = "DATABASE_SAVING"
const DATABASE_INSPECTING = "DATABASE_INSPECTING"
const ERROR = "ERROR"

export {
    ADD_TODO,
    REMOVE_TODO,
    MARK_COMPLETE,
    GET_TODOS,
    DATABASE_SAVING,
    DATABASE_INSPECTING,
    ERROR
}