const ADD_TODO = "ADD_TODO"
const REMOVE_TODO = "REMOVE_TODO"
const MARK_COMPLETE = "MARK_COMPLETE"
const FETCH_TODOS = "FETCH_TODOS"
const ERROR = "ERROR"
const LOADING_DATA = "LOADING_DATA"

export {
    ADD_TODO,
    REMOVE_TODO,
    MARK_COMPLETE,
    FETCH_TODOS,
    ERROR,
    LOADING_DATA
}